version: '3.1'

networks:
  cocktail-sql:

services:
#  cocktail-bot:
##    depends_on:
#      - test_tgdb
#    build:
#      context: .
#    networks:
#      - cocktail-sql
#    restart: always
  test_tgdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test_cocktailtb_db'
      MYSQL_USER: 'test_cocktailtb_db_user'
      MYSQL_PASSWORD: 'test_cocktailtb_db_password'
      MYSQL_ROOT_PASSWORD: 'Mamuka45'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - cocktail-sql
